# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.6
  - 3.5
  - 3.4

# Command to install dependencies
install: pip install -U tox-travis

# Command to run tests
script: tox

deploy:

  # Automatically deploy releases to PyPI for each tagged commit
  # Assuming you have installed the travis-ci CLI tool, after you
  # create the Github repo and add it to Travis, run the
  # following command to finish PyPI deployment setup:
  # $ travis encrypt MY_PYPI_PASSWORD
  # and then copy the (really long) encrypted password as shown.
  - provider: pypi
    distributions: sdist bdist_wheel
    user: amontanez24
    password:
      secure: PLEASE_REPLACE_ME
    on:
      tags: true
      repo: HDI-Project/sdv
      python: 3.6

  # Automatically build and deploy documentation to GitHub Pages after every
  # commit
  # Follow the instructions at https://docs.travis-ci.com/user/deployment/pages/
  # to setup a personal deployment token and then provide it as a secure
  # environment variable at https://travis-ci.org/HDI-Project/sdv/settings
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: true
    local-dir: docs/_build/html
    target-branch: gh-pages
    on:
      branch: master
      python: 3.6

