# Config file for automatic testing at travis-ci.org
dist: bionic
language: python
os:
  - linux
  - osx
python:
  - 3.6
  - 3.7
  - 3.8
env:
  - TOXENV=lint
  - TOXENV=readme
  - TOXENV=unit
  - TOXENV=minimum
  - TOXENV=tutorials

# Command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install graphviz pandoc
  - pip install -U tox-travis codecov

after_success: codecov

script: travis_wait 60 tox
