# Config file for automatic testing at travis-ci.org
dist: bionic
language: python
python:
  - 3.8
  - 3.7
  - 3.6

# Command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install graphviz pandoc
  - pip install -U tox-travis codecov

after_success: codecov

# Command to run tests
script: tox
