name: Install Tests
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  install:
    name: ${{ matrix.python_version }} install
    strategy:
      fail-fast: true
      matrix:
        python_version: ["3.8", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - uses: actions/checkout@v4
      - name: Build package
        run: |
          make package
      - name: Install package
        run: |
          python -m pip install "unpacked_sdist/."
      - name: Test by importing packages
        run: |
          python -c "import sdv"
          python -c "import sdv;print(sdv.version.public)"
      - name: Check package conflicts
        run: |
          python -m pip check
