name: Run Tutorials

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  tutorials:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - if: matrix.os == 'ubuntu-latest'
      name: Install dependencies - Ubuntu
      run: sudo apt-get install graphviz
    - if: matrix.os == 'macos-latest'
      name: Install dependencies - MacOS
      run: brew install graphviz
    - if: matrix.os == 'windows-latest'
      name: Install dependencies - Windows
      run: |
        python -m pip install 'torch==1.8.0' -f https://download.pytorch.org/whl/cpu/torch/
        python -m pip install 'torchvision==0.9.0' -f https://download.pytorch.org/whl/cpu/torchvision/
        choco install graphviz
    - name: Install package and dependencies
      run: pip install invoke jupyter .

    - name: Install NBConvert
      run: pip install nbconvert==6.4.5 nbformat==5.4.0
    - name: invoke tutorials
      run: invoke tutorials
